# time to wait before every movement by the computer
delayBetweenActions: 0.6

# global confidence for screen scraping
globalConfidence: 0.99

# use `False` or `True`
# require confirmation before joining class
requireConfirmation: False

# use `False` or `True`
# record classes
recordClasses: False

# in minutes
# maximum 59 minutes
timeToRecordClass: 50
