# time to wait before every movement by the computer
delayBetweenActions: 0.6

# global confidence for screen scraping
globalConfidence: 0.99

# use `False` or `True`
# require confirmation before joining class
requireConfirmationBeforeJoining: False

# use `False` or `True`
# require confirmation before leaving a class
requireConfirmationBeforeLeaving: True

# use `False` or `True`
# record classes
recordClasses: True

# in minutes
# maximum 59 minutes
timeToRecordClass: 50
