delayBetweenActions: 0.6

# use `False` or `True`
# require confirmation before joining class
requireConfirmation: True

# use `False` or `True`
# record classes
recordClasses: False

# in minutes
# maximum 59 minutes
timeToRecordClass: 50
